scrape_configs:
  - job_name: 'Book Management Job'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['192.168.1.112:8080']
        labels:
          application: 'Book Management Application'
